# Generated by Django 5.0.6 on 2024-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0003_alter_questionnaire_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('subject', 'category'), name='unique_subject_category'),
        ),
    ]
