# Generated by Django 5.0.6 on 2024-05-28 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0004_alter_questionnaire_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionnaire',
            name='unique_subject_category',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminology.subtopic'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='criminology.topic'),
        ),
    ]
