# Generated by Django 5.0.6 on 2024-06-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0007_alter_category_id_alter_questionnaire_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.category'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subtopic'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.topic'),
        ),
    ]
