# Generated by Django 5.0.6 on 2024-06-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0008_alter_questionnaire_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topictablepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicpath', models.CharField(max_length=50)),
                ('understanding', models.CharField(max_length=50)),
                ('remembering', models.CharField(max_length=50)),
                ('analyzing', models.CharField(max_length=50)),
                ('creating', models.CharField(max_length=50)),
                ('evaluating', models.CharField(max_length=50)),
                ('applying', models.CharField(max_length=50)),
            ],
        ),
    ]
