# Generated by Django 5.0.6 on 2024-06-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0009_topictablepath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topictablepath',
        ),
        migrations.AddField(
            model_name='topic',
            name='analyzing',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='applying',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='creating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='evaluating',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='remembering',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='understanding',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
