# Generated by Django 5.0.6 on 2024-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0011_alter_topic_analyzing_alter_topic_applying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='analyzing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='applying',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='evaluating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='understanding',
            field=models.IntegerField(default=0),
        ),
    ]
