# Generated by Django 5.0.6 on 2024-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0012_alter_topic_analyzing_alter_topic_applying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='totals',
            field=models.IntegerField(default=0),
        ),
    ]
