# Generated by Django 5.0.6 on 2024-06-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0013_topic_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='analyzing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='applying',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='creating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='evaluating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='totals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='analyzing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='applying',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='creating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='evaluating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='totals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='understanding',
            field=models.IntegerField(default=0),
        ),
    ]
