# Generated by Django 5.0.6 on 2024-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0014_subject_analyzing_subject_applying_subject_creating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='analyzing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='applying_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='creating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='evaluating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='remembering_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='totals_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='understanding_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='analyzing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='applying_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='creating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='evaluating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='remembering_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='totals_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='understanding_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='analyzing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='applying_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='creating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='evaluating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='remembering_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='totals_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='understanding_total',
            field=models.IntegerField(default=0),
        ),
    ]
