# Generated by Django 5.0.6 on 2024-06-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0015_subject_analyzing_total_subject_applying_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
