# Generated by Django 5.0.6 on 2024-06-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0017_savedgeneratedquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgeneratedquestions',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
