# Generated by Django 5.0.6 on 2024-06-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0022_remove_savedsubtopictable_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTopicTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField(null=True)),
                ('understanding', models.IntegerField(default=0)),
                ('remembering', models.IntegerField(default=0)),
                ('analyzing', models.IntegerField(default=0)),
                ('creating', models.IntegerField(default=0)),
                ('evaluating', models.IntegerField(default=0)),
                ('applying', models.IntegerField(default=0)),
                ('totals', models.IntegerField(default=0)),
                ('understanding_total', models.IntegerField(default=0)),
                ('remembering_total', models.IntegerField(default=0)),
                ('analyzing_total', models.IntegerField(default=0)),
                ('creating_total', models.IntegerField(default=0)),
                ('evaluating_total', models.IntegerField(default=0)),
                ('applying_total', models.IntegerField(default=0)),
                ('totals_total', models.IntegerField(default=0)),
            ],
        ),
    ]