# Generated by Django 5.1 on 2024-09-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0025_createstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateStudents',
            new_name='Students',
        ),
    ]
