# Generated by Django 5.1 on 2024-09-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0026_rename_createstudents_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentid',
            field=models.IntegerField(),
        ),
    ]
