# Generated by Django 5.1 on 2024-10-03 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0028_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOfSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('understanding', models.IntegerField(default=0)),
                ('remembering', models.IntegerField(default=0)),
                ('analyzing', models.IntegerField(default=0)),
                ('creating', models.IntegerField(default=0)),
                ('evaluating', models.IntegerField(default=0)),
                ('applying', models.IntegerField(default=0)),
                ('totals', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.topic')),
            ],
        ),
    ]
