# Generated by Django 5.1 on 2024-10-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0029_tableofspecification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableofspecification',
            old_name='totals',
            new_name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='analyzing',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='applying',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='creating',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='evaluating',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='remembering',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='totals',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='understanding',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='analyzing_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='applying_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='creating_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='evaluating_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='remembering_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='totals_total',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='understanding_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='analyzing_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='applying_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='creating_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='evaluating_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='remembering_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='totals_total',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='understanding_total',
        ),
        migrations.AddField(
            model_name='tableofspecification',
            name='pwd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic_subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='criminology.topic'),
        ),
        migrations.AlterField(
            model_name='tableofspecification',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_entries', to='criminology.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='criminology.subject'),
        ),
    ]
