# Generated by Django 5.1 on 2024-10-04 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0030_rename_totals_tableofspecification_number_of_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableofspecification',
            old_name='number_of_items',
            new_name='totals',
        ),
        migrations.RemoveField(
            model_name='tableofspecification',
            name='pwd',
        ),
        migrations.AddField(
            model_name='subject',
            name='analyzing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='applying',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='creating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='evaluating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='remembering',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='totals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='understanding',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='analyzing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='applying_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='creating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='evaluating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='remembering_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='totals_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='understanding_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='analyzing_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='applying_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='creating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='evaluating_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='remembering_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='totals_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='understanding_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic_subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.topic'),
        ),
        migrations.AlterField(
            model_name='tableofspecification',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
    ]
