# Generated by Django 5.1 on 2024-10-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0031_rename_number_of_items_tableofspecification_totals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofspecification',
            name='academic_year_id',
            field=models.IntegerField(null=True),
        ),
    ]
