# Generated by Django 5.1.2 on 2024-10-24 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0032_tableofspecification_academic_year_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableofspecification',
            name='academic_year_id',
        ),
        migrations.RemoveField(
            model_name='tableofspecification',
            name='totals',
        ),
    ]
