# Generated by Django 5.1.2 on 2024-10-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0033_remove_tableofspecification_academic_year_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofspecification',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear'),
        ),
    ]
