# Generated by Django 5.1.2 on 2024-10-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0034_tableofspecification_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
