# Generated by Django 5.1.2 on 2024-10-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0035_alter_academicyear_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='section',
        ),
        migrations.AddField(
            model_name='students',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear'),
        ),
    ]
