# Generated by Django 5.1.2 on 2024-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0036_remove_students_section_students_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentid',
            field=models.IntegerField(unique=True),
        ),
    ]
