# Generated by Django 5.1.2 on 2024-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0037_alter_students_studentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofspecification',
            name='group_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
