# Generated by Django 5.1.2 on 2024-11-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0040_remove_subject_analyzing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedGeneratedQuestions',
        ),
        migrations.DeleteModel(
            name='SavedSubtopicTable',
        ),
        migrations.DeleteModel(
            name='SavedTopicTable',
        ),
    ]
