# Generated by Django 5.1.2 on 2024-11-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0045_rename_sub_period_assesment_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='assesment_number',
            new_name='step_number',
        ),
    ]
