# Generated by Django 5.1.2 on 2024-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0046_rename_assesment_number_assesment_step_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='analyzing_assesment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='applying_assesment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='creating_assesment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='evaluating_assesment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='remembering_assesment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assesment',
            name='understanding_assesment',
            field=models.IntegerField(default=0),
        ),
    ]
