# Generated by Django 5.1.2 on 2024-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0047_assesment_analyzing_assesment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesment',
            name='assesment_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
