# Generated by Django 5.1.2 on 2024-11-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0048_assesment_assesment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assesment',
            old_name='analyzing_assesment',
            new_name='analyzing',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='applying_assesment',
            new_name='applying',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='creating_assesment',
            new_name='creating',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='evaluating_assesment',
            new_name='evaluating',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='remembering_assesment',
            new_name='remembering',
        ),
        migrations.RenameField(
            model_name='assesment',
            old_name='understanding_assesment',
            new_name='understanding',
        ),
    ]
