# Generated by Django 5.1.2 on 2024-11-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0050_rename_assesment_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='period',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='step_number',
        ),
        migrations.AddField(
            model_name='assessment',
            name='competencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subtopic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.topic'),
        ),
    ]
