# Generated by Django 5.1.3 on 2024-11-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0052_alter_assessment_assessment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_choice', models.CharField(max_length=1)),
                ('correct_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.questionnaire')),
            ],
        ),
    ]
