# Generated by Django 5.1.3 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0053_answerkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
