# Generated by Django 5.1.3 on 2024-11-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0054_answerkey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKeyTableOfSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('correct_choice', models.CharField(max_length=1)),
                ('correct_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.questionnaire')),
                ('tableofspecification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.tableofspecification')),
            ],
        ),
    ]
