# Generated by Django 5.1.3 on 2024-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0055_answerkeytableofspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='a',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='b',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='c',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='d',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='tos_exam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
