# Generated by Django 5.1.3 on 2024-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0056_answerkeytableofspecification_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkeytableofspecification',
            name='a',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answerkeytableofspecification',
            name='b',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answerkeytableofspecification',
            name='c',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='answerkeytableofspecification',
            name='d',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
