# Generated by Django 5.1.3 on 2024-11-18 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0058_answerkey_a_answerkey_assessment_exam_id_answerkey_b_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerKey',
            new_name='AnswerKeyAssessment',
        ),
    ]
