# Generated by Django 5.1.3 on 2024-11-19 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0060_studentsscore_answerkeyassessment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkeyassessment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
        migrations.AddField(
            model_name='answerkeytableofspecification',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
    ]
