# Generated by Django 5.1.3 on 2024-11-20 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0061_answerkeyassessment_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscore',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear'),
        ),
        migrations.AddField(
            model_name='studentsscore',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
