# Generated by Django 5.1.3 on 2024-11-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0062_studentsscore_academic_year_studentsscore_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscore',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsscore',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsscore',
            name='studentid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
