# Generated by Django 5.1.3 on 2024-11-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0065_categoriescountpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='analyzing_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='applying_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='creating_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='evaluating_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='remembering_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoriescountpercentage',
            name='understanding_ave_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
