# Generated by Django 5.1.3 on 2024-11-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0066_categoriescountpercentage_analyzing_ave_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='analyzing_ave_percentage',
            new_name='analyzing_correct_total',
        ),
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='applying_ave_percentage',
            new_name='applying_correct_total',
        ),
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='creating_ave_percentage',
            new_name='creating_correct_total',
        ),
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='evaluating_ave_percentage',
            new_name='evaluating_correct_total',
        ),
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='remembering_ave_percentage',
            new_name='remembering_correct_total',
        ),
        migrations.RenameField(
            model_name='categoriescountpercentage',
            old_name='understanding_ave_percentage',
            new_name='understanding_correct_total',
        ),
    ]
