# Generated by Django 5.1.3 on 2024-11-22 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0067_rename_analyzing_ave_percentage_categoriescountpercentage_analyzing_correct_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCountPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_q_counts_per_subject', models.IntegerField()),
                ('total_correct_counts_per_subject', models.IntegerField()),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject')),
            ],
        ),
    ]
