# Generated by Django 5.1.3 on 2024-11-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0068_subjectcountpercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcountpercentage',
            name='exam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
