# Generated by Django 5.1.3 on 2024-11-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0069_subjectcountpercentage_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcountpercentage',
            name='exam_id',
        ),
    ]
