# Generated by Django 5.1.3 on 2024-11-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0070_remove_subjectcountpercentage_exam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRestrictedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remembering', models.IntegerField(default=0)),
                ('understanding', models.IntegerField(default=0)),
                ('applying', models.IntegerField(default=0)),
                ('analyzing', models.IntegerField(default=0)),
                ('evaluating', models.IntegerField(default=0)),
                ('creating', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminology.category')),
            ],
        ),
    ]
