# Generated by Django 5.1.3 on 2024-11-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0072_delete_totalrestrictedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsScore',
            new_name='StudentsScoreTos',
        ),
    ]
