# Generated by Django 5.1.3 on 2024-11-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0074_studentsscoreassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscoretos',
            name='exam_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
