# Generated by Django 5.1.3 on 2024-11-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0075_studentsscoretos_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsscoretos',
            name='exam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
