# Generated by Django 5.1.3 on 2024-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0076_alter_studentsscoretos_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscoreassessment',
            name='exam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
