# Generated by Django 5.1.3 on 2024-11-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0077_studentsscoreassessment_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscoreassessment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
        migrations.AddField(
            model_name='studentsscoretos',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject'),
        ),
    ]
