# Generated by Django 5.1.3 on 2024-11-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0078_studentsscoreassessment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsscoretos',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.answerkeytableofspecification'),
        ),
    ]
