# Generated by Django 5.1.3 on 2024-11-26 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0081_alter_studentsscoreassessment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscoreassessment',
            name='stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.students'),
        ),
        migrations.AddField(
            model_name='studentsscoretos',
            name='stud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.students'),
        ),
    ]
