# Generated by Django 5.1.3 on 2024-11-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0082_studentsscoreassessment_stud_studentsscoretos_stud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsscoreassessment',
            name='studentid',
        ),
        migrations.RemoveField(
            model_name='studentsscoretos',
            name='studentid',
        ),
    ]
