# Generated by Django 5.1.3 on 2024-11-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0083_remove_studentsscoreassessment_studentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsscoreassessment',
            name='studentid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentsscoretos',
            name='studentid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
