# Generated by Django 5.1.3 on 2024-11-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0087_remove_studentsscoreassessment_stud_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsscoreassessment',
            unique_together={('studentid', 'period')},
        ),
    ]
