# Generated by Django 5.1.3 on 2024-11-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0089_answerkeyassessment_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectcountpercentage',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear'),
        ),
    ]
