# Generated by Django 5.1.3 on 2024-11-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0090_subjectcountpercentage_academic_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categoriesCountPercentage',
            new_name='CategoriesCountPercentageAssessment',
        ),
        migrations.RenameModel(
            old_name='SubjectCountPercentage',
            new_name='SubjectCountPercentageAssessment',
        ),
        migrations.CreateModel(
            name='CategoriesCountPercentageTos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remembering', models.IntegerField()),
                ('creating', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('applying', models.IntegerField()),
                ('analyzing', models.IntegerField()),
                ('evaluating', models.IntegerField()),
                ('remembering_correct_total', models.IntegerField(blank=True, null=True)),
                ('creating_correct_total', models.IntegerField(blank=True, null=True)),
                ('understanding_correct_total', models.IntegerField(blank=True, null=True)),
                ('applying_correct_total', models.IntegerField(blank=True, null=True)),
                ('analyzing_correct_total', models.IntegerField(blank=True, null=True)),
                ('evaluating_correct_total', models.IntegerField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCountPercentageTos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_q_counts_per_subject', models.IntegerField()),
                ('total_correct_counts_per_subject', models.IntegerField()),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.academicyear')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='criminology.subject')),
            ],
        ),
    ]
