# Generated by Django 5.1.3 on 2024-11-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criminology', '0091_rename_categoriescountpercentage_categoriescountpercentageassessment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriesCountPercentageTos',
            new_name='CategoriesCountPercentage',
        ),
        migrations.RenameModel(
            old_name='SubjectCountPercentageTos',
            new_name='SubjectCountPercentage',
        ),
        migrations.RemoveField(
            model_name='subjectcountpercentageassessment',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='subjectcountpercentageassessment',
            name='subject',
        ),
        migrations.DeleteModel(
            name='CategoriesCountPercentageAssessment',
        ),
        migrations.DeleteModel(
            name='SubjectCountPercentageAssessment',
        ),
    ]
